CREATE OR REPLACE PROCEDURE test_procedure(value VARCHAR)
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO menu (TEST_ID,TEST_TYPE) VALUES (1001,'Ice Cream');
    RETURN 'Insert successful';
END;
$$